INSERT INTO dim_place_mstr (City_ID, City) VALUES (1, 'Henderson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (2, 'Los Angeles');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (3, 'Fort Lauderdale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (4, 'Concord');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (5, 'Seattle');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (6, 'Fort Worth');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (7, 'Madison');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (8, 'West Jordan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (9, 'San Francisco');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (10, 'Fremont');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (11, 'Philadelphia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (12, 'Orem');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (13, 'Houston');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (14, 'Richardson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (15, 'Naperville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (16, 'Melbourne');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (17, 'Eagan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (18, 'Westland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (19, 'Dover');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (20, 'New Albany');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (21, 'New York City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (22, 'Troy');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (23, 'Chicago');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (24, 'Gilbert');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (25, 'Springfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (26, 'Jackson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (27, 'Memphis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (28, 'Decatur');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (29, 'Durham');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (30, 'Columbia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (31, 'Rochester');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (32, 'Minneapolis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (33, 'Portland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (34, 'Saint Paul');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (35, 'Aurora');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (36, 'Charlotte');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (37, 'Orland Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (38, 'Urbandale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (39, 'Columbus');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (40, 'Bristol');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (41, 'Wilmington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (42, 'Bloomington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (43, 'Phoenix');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (44, 'Roseville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (45, 'Independence');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (46, 'Pasadena');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (47, 'Newark');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (48, 'Franklin');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (49, 'Scottsdale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (50, 'San Jose');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (51, 'Edmond');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (52, 'Carlsbad');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (53, 'San Antonio');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (54, 'Monroe');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (55, 'Fairfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (56, 'Grand Prairie');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (57, 'Redlands');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (58, 'Hamilton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (59, 'Westfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (60, 'Akron');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (61, 'Denver');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (62, 'Dallas');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (63, 'Whittier');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (64, 'Saginaw');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (65, 'Medina');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (66, 'Dublin');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (67, 'Detroit');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (68, 'Tampa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (69, 'Santa Clara');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (70, 'Lakeville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (71, 'San Diego');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (72, 'Brentwood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (73, 'Chapel Hill');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (74, 'Morristown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (75, 'Cincinnati');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (76, 'Inglewood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (77, 'Tamarac');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (78, 'Colorado Springs');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (79, 'Belleville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (80, 'Taylor');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (81, 'Lakewood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (82, 'Arlington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (83, 'Arvada');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (84, 'Hackensack');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (85, 'Saint Petersburg');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (86, 'Long Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (87, 'Hesperia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (88, 'Murfreesboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (89, 'Layton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (90, 'Austin');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (91, 'Lowell');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (92, 'Manchester');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (93, 'Harlingen');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (94, 'Tucson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (95, 'Quincy');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (96, 'Pembroke Pines');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (97, 'Des Moines');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (98, 'Peoria');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (99, 'Las Vegas');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (100, 'Warwick');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (101, 'Miami');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (102, 'Huntington Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (103, 'Richmond');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (104, 'Louisville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (105, 'Lawrence');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (106, 'Canton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (107, 'New Rochelle');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (108, 'Gastonia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (109, 'Jacksonville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (110, 'Auburn');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (111, 'Norman');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (112, 'Park Ridge');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (113, 'Amarillo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (114, 'Lindenhurst');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (115, 'Huntsville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (116, 'Fayetteville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (117, 'Costa Mesa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (118, 'Parker');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (119, 'Atlanta');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (120, 'Gladstone');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (121, 'Great Falls');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (122, 'Lakeland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (123, 'Montgomery');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (124, 'Mesa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (125, 'Green Bay');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (126, 'Anaheim');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (127, 'Marysville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (128, 'Salem');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (129, 'Laredo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (130, 'Grove City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (131, 'Dearborn');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (132, 'Warner Robins');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (133, 'Vallejo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (134, 'Mission Viejo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (135, 'Rochester Hills');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (136, 'Plainfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (137, 'Sierra Vista');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (138, 'Vancouver');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (139, 'Cleveland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (140, 'Tyler');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (141, 'Burlington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (142, 'Waynesboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (143, 'Chester');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (144, 'Cary');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (145, 'Palm Coast');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (146, 'Mount Vernon');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (147, 'Hialeah');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (148, 'Oceanside');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (149, 'Evanston');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (150, 'Trenton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (151, 'Cottage Grove');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (152, 'Bossier City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (153, 'Lancaster');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (154, 'Asheville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (155, 'Lake Elsinore');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (156, 'Omaha');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (157, 'Edmonds');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (158, 'Santa Ana');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (159, 'Milwaukee');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (160, 'Florence');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (161, 'Lorain');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (162, 'Linden');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (163, 'Salinas');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (164, 'New Brunswick');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (165, 'Garland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (166, 'Norwich');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (167, 'Alexandria');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (168, 'Toledo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (169, 'Farmington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (170, 'Riverside');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (171, 'Torrance');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (172, 'Round Rock');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (173, 'Boca Raton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (174, 'Virginia Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (175, 'Murrieta');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (176, 'Olympia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (177, 'Washington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (178, 'Jefferson City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (179, 'Saint Peters');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (180, 'Rockford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (181, 'Brownsville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (182, 'Yonkers');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (183, 'Oakland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (184, 'Clinton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (185, 'Encinitas');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (186, 'Roswell');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (187, 'Jonesboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (188, 'Antioch');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (189, 'Homestead');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (190, 'La Porte');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (191, 'Lansing');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (192, 'Cuyahoga Falls');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (193, 'Reno');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (194, 'Harrisonburg');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (195, 'Escondido');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (196, 'Royal Oak');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (197, 'Rockville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (198, 'Coral Springs');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (199, 'Buffalo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (200, 'Boynton Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (201, 'Gulfport');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (202, 'Fresno');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (203, 'Greenville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (204, 'Macon');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (205, 'Cedar Rapids');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (206, 'Providence');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (207, 'Pueblo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (208, 'Deltona');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (209, 'Murray');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (210, 'Middletown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (211, 'Freeport');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (212, 'Pico Rivera');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (213, 'Provo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (214, 'Pleasant Grove');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (215, 'Smyrna');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (216, 'Parma');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (217, 'Mobile');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (218, 'New Bedford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (219, 'Irving');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (220, 'Vineland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (221, 'Glendale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (222, 'Niagara Falls');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (223, 'Thomasville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (224, 'Westminster');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (225, 'Coppell');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (226, 'Pomona');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (227, 'North Las Vegas');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (228, 'Allentown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (229, 'Tempe');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (230, 'Laguna Niguel');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (231, 'Bridgeton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (232, 'Everett');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (233, 'Watertown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (234, 'Appleton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (235, 'Bellevue');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (236, 'Allen');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (237, 'El Paso');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (238, 'Grapevine');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (239, 'Carrollton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (240, 'Kent');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (241, 'Lafayette');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (242, 'Tigard');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (243, 'Skokie');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (244, 'Plano');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (245, 'Suffolk');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (246, 'Indianapolis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (247, 'Bayonne');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (248, 'Greensboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (249, 'Baltimore');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (250, 'Kenosha');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (251, 'Olathe');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (252, 'Tulsa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (253, 'Redmond');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (254, 'Raleigh');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (255, 'Muskogee');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (256, 'Meriden');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (257, 'Bowling Green');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (258, 'South Bend');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (259, 'Spokane');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (260, 'Keller');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (261, 'Port Orange');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (262, 'Medford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (263, 'Charlottesville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (264, 'Missoula');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (265, 'Apopka');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (266, 'Reading');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (267, 'Broomfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (268, 'Paterson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (269, 'Oklahoma City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (270, 'Chesapeake');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (271, 'Lubbock');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (272, 'Johnson City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (273, 'San Bernardino');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (274, 'Leominster');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (275, 'Bozeman');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (276, 'Perth Amboy');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (277, 'Ontario');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (278, 'Rancho Cucamonga');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (279, 'Moorhead');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (280, 'Mesquite');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (281, 'Stockton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (282, 'Ormond Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (283, 'Sunnyvale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (284, 'York');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (285, 'College Station');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (286, 'Saint Louis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (287, 'Manteca');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (288, 'San Angelo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (289, 'Salt Lake City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (290, 'Knoxville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (291, 'Little Rock');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (292, 'Lincoln Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (293, 'Marion');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (294, 'Littleton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (295, 'Bangor');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (296, 'Southaven');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (297, 'New Castle');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (298, 'Midland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (299, 'Sioux Falls');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (300, 'Fort Collins');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (301, 'Clarksville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (302, 'Sacramento');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (303, 'Thousand Oaks');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (304, 'Malden');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (305, 'Holyoke');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (306, 'Albuquerque');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (307, 'Sparks');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (308, 'Coachella');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (309, 'Elmhurst');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (310, 'Passaic');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (311, 'North Charleston');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (312, 'Newport News');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (313, 'Jamestown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (314, 'Mishawaka');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (315, 'La Quinta');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (316, 'Tallahassee');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (317, 'Nashville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (318, 'Bellingham');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (319, 'Woodstock');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (320, 'Haltom City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (321, 'Wheeling');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (322, 'Summerville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (323, 'Hot Springs');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (324, 'Englewood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (325, 'Las Cruces');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (326, 'Hoover');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (327, 'Frisco');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (328, 'Vacaville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (329, 'Waukesha');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (330, 'Bakersfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (331, 'Pompano Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (332, 'Corpus Christi');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (333, 'Redondo Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (334, 'Orlando');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (335, 'Orange');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (336, 'Lake Charles');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (337, 'Highland Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (338, 'Hempstead');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (339, 'Noblesville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (340, 'Apple Valley');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (341, 'Mount Pleasant');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (342, 'Sterling Heights');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (343, 'Eau Claire');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (344, 'Pharr');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (345, 'Billings');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (346, 'Gresham');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (347, 'Chattanooga');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (348, 'Meridian');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (349, 'Bolingbrook');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (350, 'Maple Grove');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (351, 'Woodland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (352, 'Missouri City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (353, 'Pearland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (354, 'San Mateo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (355, 'Grand Rapids');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (356, 'Visalia');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (357, 'Overland Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (358, 'Temecula');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (359, 'Yucaipa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (360, 'Revere');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (361, 'Conroe');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (362, 'Tinley Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (363, 'Dubuque');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (364, 'Dearborn Heights');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (365, 'Santa Fe');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (366, 'Hickory');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (367, 'Carol Stream');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (368, 'Saint Cloud');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (369, 'North Miami');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (370, 'Plantation');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (371, 'Port Saint Lucie');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (372, 'Rock Hill');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (373, 'Odessa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (374, 'West Allis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (375, 'Chula Vista');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (376, 'Manhattan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (377, 'Altoona');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (378, 'Thornton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (379, 'Champaign');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (380, 'Texarkana');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (381, 'Edinburg');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (382, 'Baytown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (383, 'Greenwood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (384, 'Woonsocket');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (385, 'Superior');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (386, 'Bedford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (387, 'Covington');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (388, 'Broken Arrow');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (389, 'Miramar');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (390, 'Hollywood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (391, 'Deer Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (392, 'Wichita');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (393, 'Mcallen');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (394, 'Iowa City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (395, 'Boise');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (396, 'Cranston');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (397, 'Port Arthur');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (398, 'Citrus Heights');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (399, 'The Colony');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (400, 'Daytona Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (401, 'Bullhead City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (402, 'Portage');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (403, 'Fargo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (404, 'Elkhart');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (405, 'San Gabriel');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (406, 'Margate');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (407, 'Sandy Springs');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (408, 'Mentor');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (409, 'Lawton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (410, 'Hampton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (411, 'Rome');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (412, 'La Crosse');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (413, 'Lewiston');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (414, 'Hattiesburg');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (415, 'Danville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (416, 'Logan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (417, 'Waterbury');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (418, 'Athens');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (419, 'Avondale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (420, 'Marietta');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (421, 'Yuma');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (422, 'Wausau');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (423, 'Pasco');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (424, 'Oak Park');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (425, 'Pensacola');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (426, 'League City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (427, 'Gaithersburg');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (428, 'Lehi');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (429, 'Tuscaloosa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (430, 'Moreno Valley');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (431, 'Georgetown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (432, 'Loveland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (433, 'Chandler');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (434, 'Helena');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (435, 'Kirkwood');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (436, 'Waco');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (437, 'Frankfort');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (438, 'Bethlehem');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (439, 'Grand Island');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (440, 'Woodbury');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (441, 'Rogers');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (442, 'Clovis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (443, 'Jupiter');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (444, 'Santa Barbara');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (445, 'Cedar Hill');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (446, 'Norfolk');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (447, 'Draper');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (448, 'Ann Arbor');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (449, 'La Mesa');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (450, 'Pocatello');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (451, 'Holland');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (452, 'Milford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (453, 'Buffalo Grove');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (454, 'Lake Forest');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (455, 'Redding');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (456, 'Chico');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (457, 'Utica');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (458, 'Conway');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (459, 'Cheyenne');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (460, 'Owensboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (461, 'Caldwell');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (462, 'Kenner');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (463, 'Nashua');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (464, 'Bartlett');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (465, 'Redwood City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (466, 'Lebanon');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (467, 'Santa Maria');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (468, 'Des Plaines');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (469, 'Longview');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (470, 'Hendersonville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (471, 'Waterloo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (472, 'Cambridge');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (473, 'Palatine');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (474, 'Beverly');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (475, 'Eugene');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (476, 'Oxnard');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (477, 'Renton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (478, 'Glenview');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (479, 'Delray Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (480, 'Commerce City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (481, 'Texas City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (482, 'Wilson');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (483, 'Rio Rancho');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (484, 'Goldsboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (485, 'Montebello');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (486, 'El Cajon');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (487, 'Beaumont');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (488, 'West Palm Beach');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (489, 'Abilene');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (490, 'Normal');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (491, 'Saint Charles');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (492, 'Camarillo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (493, 'Hillsboro');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (494, 'Burbank');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (495, 'Modesto');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (496, 'Garden City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (497, 'Atlantic City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (498, 'Longmont');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (499, 'Davis');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (500, 'Morgan Hill');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (501, 'Clifton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (502, 'Sheboygan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (503, 'East Point');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (504, 'Rapid City');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (505, 'Andover');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (506, 'Kissimmee');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (507, 'Shelton');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (508, 'Danbury');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (509, 'Sanford');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (510, 'San Marcos');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (511, 'Greeley');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (512, 'Mansfield');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (513, 'Elyria');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (514, 'Twin Falls');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (515, 'Coral Gables');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (516, 'Romeoville');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (517, 'Marlborough');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (518, 'Laurel');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (519, 'Bryan');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (520, 'Pine Bluff');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (521, 'Aberdeen');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (522, 'Hagerstown');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (523, 'East Orange');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (524, 'Arlington Heights');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (525, 'Oswego');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (526, 'Coon Rapids');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (527, 'San Clemente');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (528, 'San Luis Obispo');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (529, 'Springdale');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (530, 'Lodi');
INSERT INTO dim_place_mstr (City_ID, City) VALUES (531, 'Mason');
